### Check the night and day prices
- platform: template
  sensors:
    cheap_next_night_or_next_day:
      friendly_name: "Cheap next night or next day"
      value_template: >-
        {{ (states('input_number.night_4h_saved') | float) <= (states('input_number.day_4h_saved') | float) }}
